In [ ]:
import numpy as np

# AX = f => X = A^(-1) * f
n = 3
A = np.random.rand(n, n)
f = np.random.rand(n, 1)
print('A')
print(A)
print('f')
print(f)

if (np.linalg.det(A) == 0):
    print("Матрица A вырожденная => обратной матрицы не существует!")
else:
    B = np.linalg.inv(A)
    X = B @ f
    print('X')
    print(X)

if (np.linalg.det(A) == 0):
    print("Матрица A вырожденная => обратной матрицы не существует!")
else:
    X = np.zeros(n)
    det_A = np.linalg.det(A)
    for i in range(n):
        Ai = A.copy()
        Ai[:, i] = f.flatten()
        det_Ai = np.linalg.det(Ai)
        X[i] = det_Ai / det_A
    print('X')
    print(X.reshape(n, 1))

A
[[0.69714525 0.3766902  0.70473528]
 [0.68774759 0.65636117 0.17320243]
 [0.81429611 0.22545588 0.90842217]]
f
[[0.8244797 ]
 [0.73219964]
 [0.42024697]]
X
[[-2.58727144]
 [ 3.30918915]
 [ 1.96051567]]
X
[[-2.58727144]
 [ 3.30918915]
 [ 1.96051567]]


In [ ]:
def gauss_method(A, f):
    n = len(f)
    B = np.hstack((A, f))
    # Прямой ход метода Гаусса
    for column in range(n):
        # Нормализация текущей строки
        B[column] = B[column] / B[column, column]
        # Исключение переменной из других строк
        for row in range(column + 1, n):
            factor = B[row, column]
            B[row] -= factor * B[column]

    # Обратный ход метода Гаусса
    X = np.zeros(n)
    for row in reversed(range(n)):
        X[row] = B[row, -1] - np.dot(B[row, row+1:n], X[row+1:])

    return X

In [ ]:
n = 3
A = np.random.rand(n, n)
f = np.random.rand(n, 1)

def gauss_method_modified(A, f):
    n = len(f)
    B = np.hstack((A, f))
    # Прямой ход метода Гаусса
    for column in range(n):
        # Выбор главного элемента (поиск максимального в текущем столбце)
        max_row = np.argmax(np.abs(B[column:, column])) + column
        # Перестановка строк, если нужно
        if max_row != column:
            B[[column, max_row]] = B[[max_row, column]]
        # Нормализация текущей строки
        B[column] = B[column] / B[column, column]
        # Исключение переменной из других строк
        for row in range(column + 1, n):
            factor = B[row, column]
            B[row] -= factor * B[column]

    # Обратный ход метода Гаусса
    X = np.zeros(n)
    for row in reversed(range(n)):
        X[row] = B[row, -1] - np.dot(B[row, row+1:n], X[row+1:])

    return X

print("Матрица A:")
print(A)
print("\nВектор f:")
print(f)
print("\nВектор X:")
print(gauss_method(A, f).reshape(n, 1))
print("\nПроверка")
print(np.linalg.solve(A, f))

Матрица A:
[[0.90508283 0.59860007 0.27631784]
 [0.66108702 0.1520286  0.88298485]
 [0.92556834 0.11123318 0.52838312]]

Вектор f:
[[0.21786403]
 [0.51156111]
 [0.03148817]]

Вектор X:
[[-0.54879384]
 [ 0.80023361]
 [ 0.85245314]]

Проверка
[[-0.54879384]
 [ 0.80023361]
 [ 0.85245314]]


In [ ]:
n = 3
A = np.random.rand(n, n)
X = np.random.rand(n, 1)
f = A @ X

print(f"cond(A) = {np.linalg.cond(A)}")

print("\nМатрица A:")
print(A)
print("\nВектор f:")
print(f)
print("\nВектор X:")
print(X)

if (np.linalg.det(A) == 0):
    print("Матрица A вырожденная => обратной матрицы не существует!")
else:
    B = np.linalg.inv(A)
    X = B @ f
    print('X')
    print(X)

if (np.linalg.det(A) == 0):
    print("Матрица A вырожденная => обратной матрицы не существует!")
else:
    X = np.zeros(n)
    det_A = np.linalg.det(A)
    for i in range(n):
        Ai = A.copy()
        Ai[:, i] = f.flatten()
        det_Ai = np.linalg.det(Ai)
        X[i] = det_Ai / det_A
    print('X')
    print(X.reshape(n, 1))


cond(A) = 21.21802439825698

Матрица A:
[[0.22434194 0.46623861 0.72586256]
 [0.60690161 0.29193504 0.7862606 ]
 [0.13935381 0.18099274 0.44578416]]

Вектор f:
[[0.59166507]
 [0.61919681]
 [0.31795399]]

Вектор X:
[[0.19452353]
 [0.43400347]
 [0.47622804]]
X
[[0.19452353]
 [0.43400347]
 [0.47622804]]
X
[[0.19452353]
 [0.43400347]
 [0.47622804]]


In [ ]:
n = 3
A = np.random.rand(n, n)
f = np.random.rand(n, 1)
print("Матрица A:")
print(A)
print("\nВектор f:")
print(f)
print("\nВектор X:")
print(gauss_method(A, f).reshape(n, 1))
print("\nПроверка")
print(np.linalg.solve(A, f))

print(np.linalg.norm(gauss_method(A, f).reshape(n, 1) - np.linalg.solve(A, f)))

Матрица A:
[[0.92302395 0.10374728 0.37660562]
 [0.04275805 0.93281241 0.19157717]
 [0.98529752 0.25532529 0.36079849]]

Вектор f:
[[0.78453648]
 [0.82939231]
 [0.33475987]]

Вектор X:
[[-2.7915773 ]
 [-0.86483176]
 [ 9.16330753]]

Проверка
[[-2.7915773 ]
 [-0.86483176]
 [ 9.16330753]]
9.305364597889226e-15


In [ ]:
n = 3
A = np.random.rand(n, n)
X1 = np.random.rand(n, 1)
f = A @ X1

print(f"cond(A) = {np.linalg.cond(A)}")

print("\nМатрица A:")
print(A)
print("\nВектор f:")
print(f)
print("\nВектор X:")
print(X1.reshape(n, 1))

if (np.linalg.det(A) == 0):
    print("Матрица A вырожденная => обратной матрицы не существует!")
else:
    B = np.linalg.inv(A)
    X = B @ f
    print("Метод обратной матрицы: ", end='')
    print(np.linalg.norm(X1.reshape(n, 1) - X.reshape(n, 1)))

if (np.linalg.det(A) == 0):
    print("Матрица A вырожденная => обратной матрицы не существует!")
else:
    X = np.zeros(n)
    det_A = np.linalg.det(A)
    for i in range(n):
        Ai = A.copy()
        Ai[:, i] = f.flatten()
        det_Ai = np.linalg.det(Ai)
        X[i] = det_Ai / det_A
    print(X.reshape(n, 1))
    print("Метод Крамера: ", end='')
    print(np.linalg.norm(X1.reshape(n, 1) - X.reshape(n, 1)))

print("Обычный метод Гаусса: ", end='')
print(np.linalg.norm(X1.reshape(n, 1) - gauss_method(A, f).reshape(n, 1)))

print("Метод Гаусса с выбором главного элемента: ", end='')
print(np.linalg.norm(X1.reshape(n, 1) - gauss_method_modified(A, f).reshape(n, 1)))

cond(A) = 8.458478050606923

Матрица A:
[[0.36136492 0.5795717  0.26758751]
 [0.93512893 0.77242841 0.44777638]
 [0.27578756 0.26720739 0.71599028]]

Вектор f:
[[0.96679462]
 [1.76538467]
 [0.82278299]]

Вектор X:
[[0.95916442]
 [0.85791411]
 [0.45952632]]
Метод обратной матрицы: 1.1157603309187458e-15
[[0.95916442]
 [0.85791411]
 [0.45952632]]
Метод Крамера: 4.335559509131367e-16
Обычный метод Гаусса: 6.304854800243424e-16
Метод Гаусса с выбором главного элемента: 6.304854800243424e-16
